# Generated by Django 4.0.3 on 2022-04-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=100)),
                ('morning_activity', models.CharField(max_length=100)),
                ('lunch', models.CharField(max_length=100)),
                ('afternoon_activity', models.CharField(max_length=100)),
                ('dinner', models.CharField(max_length=100)),
                ('night_time_activity', models.CharField(max_length=100)),
                ('planner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.planner')),
            ],
        ),
    ]
